name = "CSE290Q"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CSE290Q"]

[leanOptions]
pp.unicode.fun = false # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "CSE290Q"
